services:
  postgres:
    image: postgres
    container_name: ${CONTAINER_NAME}
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}